# Generated by Django 5.0.4 on 2024-04-11 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_faq_delete_testimonial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faq',
            old_name='reponses',
            new_name='reponse',
        ),
    ]
