# Generated by Django 5.0.4 on 2024-04-12 09:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_category_tags_courses_delete_realisation'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='image',
            field=models.ImageField(default='', upload_to='courses'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courses',
            name='programs_training',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='courses',
            name='start_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
