# Generated by Django 5.0.4 on 2024-04-13 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_course_tags_course_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('logo', models.ImageField(upload_to='logo')),
                ('logo_whitr', models.ImageField(upload_to='logo')),
                ('phone_number', models.CharField(max_length=225)),
                ('email1', models.EmailField(max_length=254)),
                ('email2', models.EmailField(max_length=254)),
                ('linkedin', models.URLField()),
                ('youtube', models.URLField()),
                ('facebook', models.URLField()),
            ],
        ),
    ]
