# Generated by Django 5.0.4 on 2024-04-13 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_course_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimony',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to='test')),
                ('content', models.TextField()),
                ('title', models.CharField(max_length=255)),
            ],
        ),
    ]
