# Generated by Django 5.0.4 on 2024-04-18 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_enquiremodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='AffiliatePartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=225)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('Referrer_name', models.CharField(max_length=255)),
                ('Referrer_email', models.CharField(max_length=255)),
                ('Referrer_phone_number', models.CharField(max_length=255)),
                ('course_name', models.CharField(max_length=255)),
                ('message', models.TextField(blank=True)),
                ('country', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('zipcode', models.CharField(max_length=255)),
            ],
        ),
    ]
